// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class AnimationMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new CharacterPropertyMetadata("Character")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new ColorEnumPropertyMetadata("Color")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new ColorEnumPropertyMetadata("AlternateColor")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Sequence")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
            };
        }
    }
}
