// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class ClassSpellMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("SpellName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("CharacterClassName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Level")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("ManaCost")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("BaseFailure")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("FirstCastExperience")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
            };
        }
    }
}
