// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class DungeonMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("BaseOffset")
                {
                    DefaultValue = null,
                    Description = "Returns base offset (difficulty) for the dungeon.",
                    IsNullable = false,
                },
                new StringPropertyMetadata("BiasMonsterFilterName")
                {
                    DefaultValue = null,
                    Description = "Returns the name of the monster filter to be used for a bias for generating monsters; or null, if the dungeon has no biasness.  Returns null, by default.",
                    IsNullable = true,
                },
                new StringArrayPropertyMetadata("DungeonGuardianNames")
                {
                    DefaultValue = null,
                    Description = "Returns all of the quests associated to the dungeon.",
                    IsNullable = true,
                },
                new StringPropertyMetadata("MapSymbol")
                {
                    DefaultValue = null,
                    Description = "The symbol used for the dungeon on the wilderness map",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("MaxLevel")
                {
                    DefaultValue = null,
                    Description = "The number of levels the dungeon has",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "The full name of the dungeon",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Shortname")
                {
                    DefaultValue = null,
                    Description = "The shortened name of the dungeon for display purposes",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Tower")
                {
                    DefaultValue = false,
                    Description = "Returns true, if the dungeon is a tower; false, otherwise.  Returns false, by default.",
                    IsNullable = false,
                },
            };
        }
    }
}
