// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class GameConfigurationMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new IntegerPropertyMetadata("MaxMessageLogLength")
                {
                    DefaultValue = 2048,
                    Description = "Returns the number of log items that the message history is allowed to store.  A null value indicates that there is no limit.  The default value is 2048.",
                    IsNullable = true,
                },
                new StringPropertyMetadata("StartupTownName")
                {
                    DefaultValue = null,
                    Description = "Returns the name of the town where the player will start, ignoring whether or not that town is a startup town; or null, for a random town to be choosen from the available startup towns.",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Towns")
                {
                    PropertyMetadatas = TownMetadata.Metadata,
                    EntityTitle = "Town",
                    KeyPropertyName = "Key",
                    Description = "Returns null, if Towns should be loaded from the assembly.  Otherwise, returns an array of Towns to be loaded into the SingletonRepository.",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Shopkeepers")
                {
                    PropertyMetadatas = ShopkeeperMetadata.Metadata,
                    EntityTitle = "Shopkeeper",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("GameCommands")
                {
                    PropertyMetadatas = GameCommandMetadata.Metadata,
                    EntityTitle = "GameCommand",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("StoreCommands")
                {
                    PropertyMetadatas = StoreCommandMetadata.Metadata,
                    EntityTitle = "StoreCommand",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("HelpGroups")
                {
                    PropertyMetadatas = HelpGroupMetadata.Metadata,
                    EntityTitle = "HelpGroup",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("MonsterRaces")
                {
                    PropertyMetadatas = MonsterRaceMetadata.Metadata,
                    EntityTitle = "MonsterRace",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Symbols")
                {
                    PropertyMetadatas = SymbolMetadata.Metadata,
                    EntityTitle = "Symbol",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Vaults")
                {
                    PropertyMetadatas = VaultMetadata.Metadata,
                    EntityTitle = "Vault",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("DungeonGuardians")
                {
                    PropertyMetadatas = DungeonGuardianMetadata.Metadata,
                    EntityTitle = "DungeonGuardian",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Dungeons")
                {
                    PropertyMetadatas = DungeonMetadata.Metadata,
                    EntityTitle = "Dungeon",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("StoreFactories")
                {
                    PropertyMetadatas = StoreFactoryMetadata.Metadata,
                    EntityTitle = "StoreFactory",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("ProjectileGraphics")
                {
                    PropertyMetadatas = ProjectileGraphicMetadata.Metadata,
                    EntityTitle = "ProjectileGraphic",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("AmuletReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("MushroomReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("PotionReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("RingReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("RodReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("ScrollReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("StaffReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("WandReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("ClassSpells")
                {
                    PropertyMetadatas = ClassSpellMetadata.Metadata,
                    EntityTitle = "ClassSpell",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("WizardCommands")
                {
                    PropertyMetadatas = WizardCommandMetadata.Metadata,
                    EntityTitle = "WizardCommand",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Tiles")
                {
                    PropertyMetadatas = TileMetadata.Metadata,
                    EntityTitle = "Tile",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Animations")
                {
                    PropertyMetadatas = AnimationMetadata.Metadata,
                    EntityTitle = "Animation",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Spells")
                {
                    PropertyMetadatas = SpellMetadata.Metadata,
                    EntityTitle = "Spell",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Plurals")
                {
                    PropertyMetadatas = PluralMetadata.Metadata,
                    EntityTitle = "Plural",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Attacks")
                {
                    PropertyMetadatas = AttackMetadata.Metadata,
                    EntityTitle = "Attack",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new CollectionPropertyMetadata("Gods")
                {
                    PropertyMetadatas = GodMetadata.Metadata,
                    EntityTitle = "God",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("ElvishTexts")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("FindQuests")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("FunnyComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("FunnyDescriptions")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("HorrificDescriptions")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("InsultPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("MoanPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("UnreadableFlavorSyllables")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("ShopkeeperAcceptedComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("ShopkeeperBargainComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("ShopkeeperGoodComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("ShopkeeperLessThanGuessComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("ShopkeeperWorthlessComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("SingingPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringsPropertyMetadata("WorshipPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
            };
        }
    }
}
