// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class MonsterRaceMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringArrayPropertyMetadata("SpellNames")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringPropertyMetadata("MultilineName")
                {
                    DefaultValue = null,
                    Description = "Returns a multiline version of the monster race that is shown to the player.  Defaults to the <see cref=\"FriendlyName\"/>.  Word-breaks are encoded with a \n character.",
                    IsNullable = true,
                },
                new StringPropertyMetadata("SymbolName")
                {
                    DefaultValue = null,
                    Description = "Returns the key for the symbol to be used.  The actual Symbol object is bound to the Symbol property during the bind phase.",
                    IsNullable = false,
                },
                new ColorEnumPropertyMetadata("Color")
                {
                    DefaultValue = ColorEnum.White,
                    Description = "The color to display the monster as.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Animal")
                {
                    DefaultValue = false,
                    Description = "The monster is an animal.",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("ArmorClass")
                {
                    DefaultValue = null,
                    Description = "The monsters armor class.",
                    IsNullable = false,
                },
                new TuplePropertyMetadata("AttackDefinitions")
                {
                    DataTypes = new PropertyMetadata[]
                    {
                        new StringPropertyMetadata("MethodName")
                        {
                            DefaultValue = null,
                            Description = "The name of the attack method.",
                            IsNullable = false,
                        },
                        new StringPropertyMetadata("EffectName")
                        {
                            DefaultValue = null,
                            Description = "The name of the attach effect.",
                            IsNullable = true,
                        },
                        new IntegerPropertyMetadata("Dice")
                        {
                            DefaultValue = null,
                            Description = "The number of dice.",
                            IsNullable = false,
                        },
                        new IntegerPropertyMetadata("Sides")
                        {
                            DefaultValue = null,
                            Description = "The number of sides on the dice.",
                            IsNullable = false,
                        },
                    },
                    Description = "Returns an array of the definitions for the attacks abilities of the monster; or null, if the monster cannot attack.  Returns null, by default.",
                    IsNullable = true,
                },
                new BooleanPropertyMetadata("AttrAny")
                {
                    DefaultValue = false,
                    Description = "The monster's color can be anything (if 'AttrMulti' is set).",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("AttrClear")
                {
                    DefaultValue = false,
                    Description = "The monster is transparent.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("AttrMulti")
                {
                    DefaultValue = false,
                    Description = "The monster changes color.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("BashDoor")
                {
                    DefaultValue = false,
                    Description = "The monster can break open doors.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("CharClear")
                {
                    DefaultValue = false,
                    Description = "The monster is never seen, even with see invisible.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("CharMulti")
                {
                    DefaultValue = false,
                    Description = "The monster is changes shape randomly.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ColdBlood")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Cthuloid")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Demon")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Description")
                {
                    DefaultValue = null,
                    Description = "The descriptive text.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Dragon")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Drop_1D2")
                {
                    DefaultValue = false,
                    Description = "The monster drops 1d2 items.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Drop_2D2")
                {
                    DefaultValue = false,
                    Description = "The monster drops 2d2 items.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Drop_3D2")
                {
                    DefaultValue = false,
                    Description = "The monster drops 3d2 items.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Drop_4D2")
                {
                    DefaultValue = false,
                    Description = "The monster drops 4d2 items.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Drop60")
                {
                    DefaultValue = false,
                    Description = "The monster drops an item 60% of the time.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Drop90")
                {
                    DefaultValue = false,
                    Description = "The monster drops an item 90% of the time.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("DropGood")
                {
                    DefaultValue = false,
                    Description = "The monster drops good items.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("DropGreat")
                {
                    DefaultValue = false,
                    Description = "The monster drops great items.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("EldritchHorror")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("EmptyMind")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Escorted")
                {
                    DefaultValue = false,
                    Description = "The monster comes with minions of the same character.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("EscortsGroup")
                {
                    DefaultValue = false,
                    Description = "The monster's minions come in groups (this doesn't force minions if 'Escort' isn't set).",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Evil")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Female")
                {
                    DefaultValue = false,
                    Description = "The monster should use feminine pronouns.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("FireAura")
                {
                    DefaultValue = false,
                    Description = "The monster has an aura of fire around it.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ForceMaxHp")
                {
                    DefaultValue = false,
                    Description = "The monster has maximum hit points.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ForceSleep")
                {
                    DefaultValue = false,
                    Description = "The monster always starts asleep.",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("FreqInate")
                {
                    DefaultValue = null,
                    Description = "The 1-in-X frequency with which the monster uses special abilities.",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("FreqSpell")
                {
                    DefaultValue = null,
                    Description = "The 1-in-X frequency with which the monster uses spells.",
                    IsNullable = false,
                },
                new StringPropertyMetadata("FriendlyName")
                {
                    DefaultValue = null,
                    Description = "The name that the game shows the player (may have duplicates).",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Friends")
                {
                    DefaultValue = false,
                    Description = "The monster comes with friends of the same race.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Giant")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Good")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("GreatOldOne")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Hdice")
                {
                    DefaultValue = null,
                    Description = "The number of hit dice the monster has.",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Hside")
                {
                    DefaultValue = null,
                    Description = "The number of sides of the monster's hit dice.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("HurtByCold")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("HurtByFire")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("HurtByLight")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("HurtByRock")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneAcid")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneCold")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneConfusion")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneFear")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneFire")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneLightning")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmunePoison")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneSleep")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ImmuneStun")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Invisible")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("KillBody")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("KillItem")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("KillWall")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("LevelFound")
                {
                    DefaultValue = null,
                    Description = "The level on which the monster is normally found.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("LightningAura")
                {
                    DefaultValue = false,
                    Description = "The monster has an aura of electricity around it.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Male")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Mexp")
                {
                    DefaultValue = null,
                    Description = "The experience value for killing one of these.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("MoveBody")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Multiply")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("NeverAttack")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("NeverMove")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Nonliving")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("NoticeRange")
                {
                    DefaultValue = null,
                    Description = "The distance at which the monster notices the player.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("OnlyDropGold")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("OnlyDropItem")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("OpenDoor")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Orc")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("PassWall")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Powerful")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("RandomMove25")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("RandomMove50")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Rarity")
                {
                    DefaultValue = null,
                    Description = "The rarity with which the monster is usually found.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Reflecting")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Regenerate")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ResistDisenchant")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ResistNether")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ResistNexus")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ResistPlasma")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ResistTeleport")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("ResistWater")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Shapechanger")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Sleep")
                {
                    DefaultValue = null,
                    Description = "How deeply the monster sleeps.",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Smart")
                {
                    DefaultValue = false,
                    Description = "Returns true, if the monster is smart.  When badly injured, the monster will want to prioritise spells that disable the player, summon help, or let it escape over spells that do direct damage.",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Speed")
                {
                    DefaultValue = null,
                    Description = "how fast the monster moves (110 = normal speed, higher is better).",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Stupid")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("TakeItem")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Troll")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Undead")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("Unique")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("WeirdMind")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
            };
        }
    }
}
