// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class ProjectileGraphicMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new CharacterPropertyMetadata("Character")
                {
                    DefaultValue = null,
                    Description = "Returns the character to be used for the projectile.",
                    IsNullable = false,
                },
                new ColorPropertyMetadata("Color")
                {
                    DefaultValue = ColorEnum.White,
                    Description = "Returns the color to be used for the projectile.",
                    IsNullable = false,
                },
            };
        }
    }
}
