// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class SpellMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "Returns the name of the spell, as rendered to the SaveGame.",
                    IsNullable = false,
                },
                new StringPropertyMetadata("CastScriptName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringPropertyMetadata("CastFailedScriptName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                },
                new StringPropertyMetadata("LearnedDetails")
                {
                    DefaultValue = "",
                    Description = "",
                    IsNullable = false,
                },
            };
        }
    }
}
