// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class TownMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new CharacterPropertyMetadata("Char")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("HousePrice")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringsPropertyMetadata("StoreFactoryNames")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("CanBeEscortedHere")
                {
                    DefaultValue = true,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("AllowStartupTown")
                {
                    DefaultValue = true,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("DungeonName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new BooleanPropertyMetadata("UnusedStoreLotsAreGraveyards")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                },
            };
        }
    }
}
