// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class VaultMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new ColorEnumPropertyMetadata("Color")
                {
                    DefaultValue = ColorEnum.White,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Category")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Height")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Rating")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new StringPropertyMetadata("Text")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
                new IntegerPropertyMetadata("Width")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                },
            };
        }
    }
}
