// <auto-generated>
// This code was generated by the AngbandOS.Core.Interface.MetaGen tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class WizardCommandMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                },
                new CharacterPropertyMetadata("KeyChar")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key Char",
                },
                new BooleanPropertyMetadata("IsEnabled")
                {
                    DefaultValue = true,
                    Description = "",
                    IsNullable = false,
                    Title = "Is Enabled",
                },
                new StringPropertyMetadata("HelpGroupName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Help Group Name",
                },
                new StringPropertyMetadata("HelpDescription")
                {
                    DefaultValue = "",
                    Description = "",
                    IsNullable = false,
                    Title = "Help Description",
                },
                new StringPropertyMetadata("ExecuteScriptName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Execute Script Name",
                },
            };
        }
    }
}
