// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”
namespace AngbandOS.Core;

internal enum AttributeEnum
{
    BaseArmorClass,
    BonusHits,
    BonusArmorClass,
    BonusDamage,
    BonusStrength,
    BonusIntelligence,
    BonusWisdom,
    BonusDexterity,
    BonusConstitution,
    BonusCharisma,
    BonusStealth,
    BonusSearch,
    BonusInfravision,
    BonusTunnel,
    BonusAttacks,
    BonusSpeed,
    Activation,
    Aggravate,
    AntiTheft,
    ArtifactBias,
    Blessed,
    Blows,
    BrandAcid,
    BrandCold,
    BrandElec,
    BrandFire,
    BrandPois,
    CanApplyBlessedArtifactBias,
    ArtifactBiasSlayingDisabled,
    CanApplyBlowsBonus,
    CanReflectBoltsAndArrows,
    CanApplySlayingBonus,
    CanApplyBonusArmorClassMiscPower,
    CanProvideSheathOfElectricity,
    CanProvideSheathOfFire,
    Chaotic,
    Color,
    DamageDice,
    DiceSides,
    DrainExp,
    DreadCurse,
    EasyKnow,
    Feather,
    FreeAct,
    FriendlyName,
    HeavyCurse,
    HideType,
    HoldLife,
    IgnoreAcid,
    IgnoreCold,
    IgnoreElec,
    IgnoreFire,
    ImAcid,
    ImCold,
    ImElec,
    ImFire,
    Impact,
    IsCursed,
    NoMagic,
    NoTele,
    PermaCurse,
    Radius,
    Reflect,
    Regen,
    ResAcid,
    ResBlind,
    ResChaos,
    ResCold,
    ResConf,
    ResDark,
    ResDisen,
    ResElec,
    ResFear,
    ResFire,
    ResLight,
    ResNether,
    ResNexus,
    ResPois,
    ResShards,
    ResSound,
    Search,
    SeeInvis,
    ShElec,
    ShFire,
    ShowMods,
    SlayAnimal,
    SlayDemon,
    SlayDragon,
    SlayEvil,
    SlayGiant,
    SlayOrc,
    SlayTroll,
    SlayUndead,
    SlowDigest,
    SustCha,
    SustCon,
    SustDex,
    SustInt,
    SustStr,
    SustWis,
    Telepathy,
    Teleport,
    TreasureRating,

    /// <summary>
    /// Returns the value of the enhancement.  Returns 0 by default.  For wands, staffs and light-sources, this value should be the value of an item with no charges.  An empty item should
    /// still have some value if it can be recharged.
    /// </summary>
    Value,

    Valueless,
    Vampiric,
    Vorpal1InChance,

    /// <summary>
    /// Returns a 1-in-chance value of the weapon doing extra vorpal attacks. Does not affect non-vorpal cutting weapons.  Default to a 1-in-4 chance.
    /// </summary>
    VorpalExtraAttacks1InChance,
    Wraith,
    Weight,
    XtraMight,
    XtraShots
}
