// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”
namespace AngbandOS.Core;

internal enum AttributeEnum
{
    Activation,
    Aggravate,
    AntiTheft,
    ArtifactBias,
    ArtifactBiasSlayingDisabled,
    Attacks,

    /// <summary>
    /// Represents the base armor class.  This armor class is always known by the player.
    /// </summary>
    BaseArmorClass,
    Blessed,
    Blows,

    /// <summary>
    /// Represents the bonus armor class. This armor class will only be known to the player, if the player if the item is known.
    /// </summary>
    BonusArmorClass,
    BrandAcid,
    BrandCold,
    BrandElec,
    BrandFire,
    BrandPois,
    CanApplyBlessedArtifactBias,
    CanApplyBlowsBonus,
    CanApplyBonusArmorClassMiscPower,
    CanApplySlayingBonus,
    CanProvideSheathOfElectricity,
    CanProvideSheathOfFire,
    CanReflectBoltsAndArrows,
    Chaotic,
    Charisma,
    Color,
    Constitution,
    DamageDice,
    Dexterity,
    DiceSides,
    DisarmTraps,
    DrainExp,
    DreadCurse,
    EasyKnow,
    Feather,
    FreeAct,
    FriendlyName,
    HatesAcid,
    HatesCold,
    HatesElectricity,
    HatesFire,
    HeavyCurse,
    HideType,
    HoldLife,
    IgnoreAcid,
    IgnoreCold,
    IgnoreElec,
    IgnoreFire,
    ImAcid,
    ImCold,
    ImElec,
    ImFire,
    Impact,
    Infravision,
    Intelligence,
    IsCursed,
    NoMagic,
    NoTele,
    PermaCurse,
    Radius,
    RangedToHit,
    Reflect,
    Regen,
    ResAcid,
    ResBlind,
    ResChaos,
    ResCold,
    ResConf,
    ResDark,
    ResDisen,
    ResElec,
    ResFear,
    ResFire,
    ResLight,
    ResNether,
    ResNexus,
    ResPois,
    ResShards,
    ResSound,
    SavingThrow ,
    Search,
    SearchFrequency,
    SeeInvis,
    ShElec,
    ShFire,
    ShowMods,
    SlayAnimal,
    SlayDemon,
    SlayDragon,
    SlayEvil,
    SlayGiant,
    SlayOrc,
    SlayTroll,
    SlayUndead,
    SlowDigest,
    Speed,
    Stealth,
    Strength,
    SustCha,
    SustCon,
    SustDex,
    SustInt,
    SustStr,
    SustWis,
    Telepathy,
    Teleport,
    ThrowingToHit,
    ToDamage,
    ToHit,
    TreasureRating,
    Tunnel,
    UseDevice,

    /// <summary>
    /// Returns the value of the enhancement.  Returns 0 by default.  For wands, staffs and light-sources, this value should be the value of an item with no charges.  An empty item should
    /// still have some value if it can be recharged.
    /// </summary>
    Value,

    Valueless,
    Vampiric,
    Vorpal1InChance,

    /// <summary>
    /// Returns a 1-in-chance value of the weapon doing extra vorpal attacks. Does not affect non-vorpal cutting weapons.  Default to a 1-in-4 chance.
    /// </summary>
    VorpalExtraAttacks1InChance,
    Wisdom,
    Wraith,
    Weight,
    XtraMight,
    XtraShots
}
