// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”
namespace AngbandOS.Core.MonsterSpells;

/// <summary>
/// Represents a monster spell that fires a projectile without any radius.  Default messages are provided.
/// </summary>
[Serializable]
internal abstract class ProjectileMonsterSpell : MonsterSpell
{
    protected ProjectileMonsterSpell(Game game) : base(game) { }

    public override void Bind(RestoreGameState? restoreGameState)
    {
        base.Bind(restoreGameState);
        Projectile = Game.SingletonRepository.Get<Projectile>(ProjectileKey);
        DamageRoll = Game.ParseNumericExpression(DamageRollExpression);
        RadiusExpression = Game.ParseNumericExpression(RadiusExpressionText);
    }

    protected virtual bool ItemProjectionFlag => false;
    protected virtual bool GridProjectionFlag => false;
    protected virtual bool KillProjectionFlag => true;
    protected virtual bool StopProjectionFlag => true;

    /// <summary>
    /// Returns the key for the projectile to use.  This property is used to bind the ProjectileProperty during the binding phase.
    /// </summary>
    protected abstract string ProjectileKey { get; }

    /// <summary>
    /// Returns the projectile that the monster will use when attacking with the spell.  This property is bound using the ProjectileKey property during the bind phase.
    /// </summary>
    /// <param name="game"></param>
    /// <returns></returns>
    protected Projectile Projectile { get; private set; }

    private (string, object)[] GetExpressionProviders(Monster monster) => new (string, object)[] 
    {
        ("MonsterLevel", Math.Max(monster.Race.Level, 1)),
        ("MonsterHealth", monster.Health)
    };

protected int Damage(Monster monster)
    {
        int damage = Game.ComputeIntegerExpression(DamageRoll, GetExpressionProviders(monster)).Value;
        if (MaxDamage.HasValue && damage > MaxDamage.Value)
        {
            damage = MaxDamage.Value;
        }
        return damage;
    }

    protected virtual int? MaxDamage { get; } = null;

    /// <summary>
    /// Returns the roll expression that determines the amount of damage the arrow projectile inflicts.  This expression is parse
    /// to generate the DamageDiceRoll.
    /// </summary>
    protected abstract string DamageRollExpression { get; }

    protected virtual string RadiusExpressionText => "0";
    protected Expression RadiusExpression { get; private set; }

    /// <summary>
    /// Returns the roll that determines the amount of damage the arrow projectile inflicts.  This dice roll is generated by
    /// parsing the DamageDiceRollExpression property during binding.
    /// </summary>
    protected Expression DamageRoll { get; private set; }

    /// <summary>
    /// Returns the radius of the damage.  Projectiles returns 0, by default.
    /// </summary>
    protected virtual int Radius(Monster monster) => Game.ComputeIntegerExpression(RadiusExpression, GetExpressionProviders(monster)).Value;

    /// <summary>
    /// Fires the projectile.  This method allows derived classes to override the projectile parameters.
    /// </summary>
    /// <param name="game"></param>
    /// <param name="who"></param>
    /// <param name="rad"></param>
    /// <param name="y"></param>
    /// <param name="x"></param>
    /// <param name="dam"></param>
    /// <param name="projectile"></param>
    /// <param name="flg"></param>
    /// <returns></returns>
    private IsNoticedEnum Project(Monster monster, int rad, int y, int x, int dam, Projectile projectile, bool grid, bool stop, bool item, bool kill)
    {
        return projectile.Fire(monster.GetMonsterIndex(), rad, Game.MapY.IntValue, Game.MapX.IntValue, dam, grid: grid, stop: stop, item: item, kill: kill, jump: false, beam: false, thru: false, hide: false);
    }

    public override void ExecuteOnPlayer(Monster monster)
    {
        int damage = Damage(monster);
        int radius = Radius(monster);
        Project(monster, radius, Game.MapY.IntValue, Game.MapX.IntValue, damage, Projectile, grid: GridProjectionFlag, stop: StopProjectionFlag, kill: KillProjectionFlag, item: ItemProjectionFlag);
    }

    public override void ExecuteOnMonster(Monster monster, Monster target)
    {
        int damage = Damage(monster);
        int radius = Radius(monster);
        Project(monster, radius, target.MapY, target.MapX, damage, Projectile, grid: GridProjectionFlag, stop: StopProjectionFlag, kill: KillProjectionFlag, item: ItemProjectionFlag);
    }
}
