// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”
namespace AngbandOS.Core;

internal enum PropertyEnum
{
    CanApplyBlessedArtifactBias,
    CanApplyArtifactBiasSlaying,
    CanApplyBlowsBonus,
    CanReflectBoltsAndArrows,
    CanApplySlayingBonus,
    CanApplyBonusArmorClassMiscPower,
    CanProvideSheathOfElectricity,
    CanProvideSheathOfFire,
    BonusHit,
    BonusArmorClass,
    BonusDamage,
    BonusStrength,
    BonusIntelligence,
    BonusWisdom,
    BonusDexterity,
    BonusConstitution,
    BonusCharisma,
    BonusStealth,
    BonusSearch,
    BonusInfravision,
    BonusTunnel,
    BonusAttacks,
    BonusSpeed,
    Activation,
    Aggravate,
    AntiTheft,
    ArtifactBias,
    Blessed,
    Blows,
    BrandAcid,
    BrandCold,
    BrandElec,
    BrandFire,
    BrandPois,
    Cha,
    Chaotic,
    Con,

    /// <summary>
    /// Returns the real cost of a standard item.  Returns 0 by default.  For wands, staffs and light-sources, this value should be the value of an item with no charges.  An empty item should
    /// still have some value if it can be recharged.
    /// </summary>
    Cost,
    IsCursed,
    Dex,
    DrainExp,
    DreadCurse,
    EasyKnow,
    Feather,
    FreeAct,
    FriendlyName,
    HeavyCurse,
    HideType,
    HoldLife,
    IgnoreAcid,
    IgnoreCold,
    IgnoreElec,
    IgnoreFire,
    ImAcid,
    ImCold,
    ImElec,
    ImFire,
    Impact,
    Infra,
    InstaArt,
    Int,
    KillDragon,
    NoMagic,
    NoTele,
    PermaCurse,
    Radius,
    Reflect,
    Regen,
    ResAcid,
    ResBlind,
    ResChaos,
    ResCold,
    ResConf,
    ResDark,
    ResDisen,
    ResElec,
    ResFear,
    ResFire,
    ResLight,
    ResNether,
    ResNexus,
    ResPois,
    ResShards,
    ResSound,
    Search,
    SeeInvis,
    ShElec,
    ShFire,
    ShowMods,
    SlayAnimal,
    SlayDemon,
    SlayDragon,
    SlayEvil,
    SlayGiant,
    SlayOrc,
    SlayTroll,
    SlayUndead,
    SlowDigest,
    Speed,
    Stealth,
    Str,
    SustCha,
    SustCon,
    SustDex,
    SustInt,
    SustStr,
    SustWis,
    Telepathy,
    Teleport,
    TreasureRating,
    Tunnel,
    Value,
    Valueless,
    Vampiric,
    Vorpal,
    Wis,
    Wraith,
    Weight,
    XtraMight,
    XtraShots
}
