"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ColourEnum = void 0;
var ColourEnum;
(function (ColourEnum) {
    ColourEnum[ColourEnum["Background"] = 0] = "Background";
    ColourEnum[ColourEnum["Black"] = 1] = "Black";
    ColourEnum[ColourEnum["Grey"] = 2] = "Grey";
    ColourEnum[ColourEnum["BrightGrey"] = 3] = "BrightGrey";
    ColourEnum[ColourEnum["Silver"] = 4] = "Silver";
    ColourEnum[ColourEnum["Beige"] = 5] = "Beige";
    ColourEnum[ColourEnum["BrightBeige"] = 6] = "BrightBeige";
    ColourEnum[ColourEnum["White"] = 7] = "White";
    ColourEnum[ColourEnum["BrightWhite"] = 8] = "BrightWhite";
    ColourEnum[ColourEnum["Red"] = 9] = "Red";
    ColourEnum[ColourEnum["BrightRed"] = 10] = "BrightRed";
    ColourEnum[ColourEnum["Copper"] = 11] = "Copper";
    ColourEnum[ColourEnum["Orange"] = 12] = "Orange";
    ColourEnum[ColourEnum["BrightOrange"] = 13] = "BrightOrange";
    ColourEnum[ColourEnum["Brown"] = 14] = "Brown";
    ColourEnum[ColourEnum["BrightBrown"] = 15] = "BrightBrown";
    ColourEnum[ColourEnum["Gold"] = 16] = "Gold";
    ColourEnum[ColourEnum["Yellow"] = 17] = "Yellow";
    ColourEnum[ColourEnum["BrightYellow"] = 18] = "BrightYellow";
    ColourEnum[ColourEnum["Chartreuse"] = 19] = "Chartreuse";
    ColourEnum[ColourEnum["BrightChartreuse"] = 20] = "BrightChartreuse";
    ColourEnum[ColourEnum["Green"] = 21] = "Green";
    ColourEnum[ColourEnum["BrightGreen"] = 22] = "BrightGreen";
    ColourEnum[ColourEnum["Turquoise"] = 23] = "Turquoise";
    ColourEnum[ColourEnum["BrightTurquoise"] = 24] = "BrightTurquoise";
    ColourEnum[ColourEnum["Blue"] = 25] = "Blue";
    ColourEnum[ColourEnum["BrightBlue"] = 26] = "BrightBlue";
    ColourEnum[ColourEnum["Diamond"] = 27] = "Diamond";
    ColourEnum[ColourEnum["Purple"] = 28] = "Purple";
    ColourEnum[ColourEnum["BrightPurple"] = 29] = "BrightPurple";
    ColourEnum[ColourEnum["Pink"] = 30] = "Pink";
    ColourEnum[ColourEnum["BrightPink"] = 31] = "BrightPink";
})(ColourEnum = exports.ColourEnum || (exports.ColourEnum = {}));
//# sourceMappingURL=colour-enum.module.js.map