' ------------------------------------------------------------------------------
' <auto-generated>
' This code was generated by a tool.
' Runtime Version:4.0.30319.42000
' 
' Changes to this file may cause incorrect behavior and will be lost if
' the code is regenerated.
' </auto-generated>
' ------------------------------------------------------------------------------

Imports System.Diagnostics
Imports Microsoft.VisualBasic


Namespace byMarc.Net2.Library.LanguageParsing.My

    <CompilerGenerated()>
    <CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")>
    <ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)>
    Friend NotInheritable Partial Class MySettings
        Inherits Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
        ' TODO ERROR: Skipped IfDirectiveTrivia
        ' #If _MyType = "WindowsForms" Then
        ' ' TODO ERROR: Skipped DisabledTextTrivia
        ' Private Shared addedHandler As Boolean
        ' 
        ' Private Shared addedHandlerLockObject As New Object
        ' 
        ' <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        ' Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        ' If My.Application.SaveMySettingsOnExit Then
        ' My.Settings.Save()
        ' End If
        ' End Sub
        ' ' TODO ERROR: Skipped EndIfDirectiveTrivia
        ' #End If
        ' 
#End Region

        Public Shared ReadOnly Property [Default] As MySettings
            Get

                ' TODO ERROR: Skipped IfDirectiveTrivia
                ' #If _MyType = "WindowsForms" Then
                ' ' TODO ERROR: Skipped DisabledTextTrivia
                ' If Not addedHandler Then
                ' SyncLock addedHandlerLockObject
                ' If Not addedHandler Then
                ' AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                ' addedHandler = True
                ' End If
                ' End SyncLock
                ' End If
                ' ' TODO ERROR: Skipped EndIfDirectiveTrivia
                ' #End If
                ' 
                Return defaultInstance
            End Get
        End Property
    End Class
End Namespace

Namespace byMarc.Net2.Library.LanguageParsing.My

    <HideModuleName()>
    <DebuggerNonUserCode()>
    <CompilerGenerated()>
    Friend Module MySettingsProperty

        <ComponentModel.Design.HelpKeyword("My.Settings")>
        Friend ReadOnly Property Settings As MySettings
            Get
                Return MySettings.Default
            End Get
        End Property
    End Module
End Namespace
