// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”
namespace AngbandOS.GamePacks.Cthangband;

[Serializable]
public class CallChaosProjectileScriptWeightedRandom : ProjectileScriptWeightedRandomGameConfiguration
{
    public override (string, int)[] NameAndWeightBindings => new (string, int)[]
    {
        (nameof(ElectricityBeamAllDirections75ProjectileScript), 3),
        (nameof(PoisonGasBeamAllDirections75ProjectileScript), 3),
        (nameof(AcidBeamAllDirections75ProjectileScript), 3),
        (nameof(ColdBeamAllDirections75ProjectileScript), 3),
        (nameof(FireBeamAllDirections75ProjectileScript), 3),
        (nameof(MissileBeamAllDirections75ProjectileScript), 3),
        (nameof(ArrowBeamAllDirections75ProjectileScript), 3),
        (nameof(PlasmaBeamAllDirections75ProjectileScript), 3),
        (nameof(HolyFireBeamAllDirections75ProjectileScript), 3),
        (nameof(WaterBeamAllDirections75ProjectileScript), 3),
        (nameof(LightBeamAllDirections75ProjectileScript), 3),
        (nameof(DarknessBeamAllDirections75ProjectileScript), 3),
        (nameof(ForceBeamAllDirections75ProjectileScript), 3),
        (nameof(InertiaBeamAllDirections75ProjectileScript), 3),
        (nameof(ManaBeamAllDirections75ProjectileScript), 3),
        (nameof(MeteorBeamAllDirections75ProjectileScript), 3),
        (nameof(IceBeamAllDirections75ProjectileScript), 3),
        (nameof(ChaosBeamAllDirections75ProjectileScript), 3),
        (nameof(NetherBeamAllDirections75ProjectileScript), 3),
        (nameof(DisenchantBeamAllDirections75ProjectileScript), 3),
        (nameof(ExplodeBeamAllDirections75ProjectileScript), 3),
        (nameof(SoundBeamAllDirections75ProjectileScript), 3),
        (nameof(NexusBeamAllDirections75ProjectileScript), 3),
        (nameof(ConfusionBeamAllDirections75ProjectileScript), 3),
        (nameof(TimeBeamAllDirections75ProjectileScript), 3),
        (nameof(GravityBeamAllDirections75ProjectileScript), 3),
        (nameof(ShardBeamAllDirections75ProjectileScript), 3),
        (nameof(NukeBeamAllDirections75ProjectileScript), 3),
        (nameof(HellfireBeamAllDirections75ProjectileScript), 3),
        (nameof(DisintegrateBeamAllDirections75ProjectileScript), 3),

        (nameof(ElectricityBallAllDirections75R2ProjectileScript), 9),
        (nameof(PoisonGasBallAllDirections75R2ProjectileScript), 9),
        (nameof(AcidBallAllDirections75R2ProjectileScript), 9),
        (nameof(ColdBallAllDirections75R2ProjectileScript), 9),
        (nameof(FireBallAllDirections75R2ProjectileScript), 9),
        (nameof(MissileBallAllDirections75R2ProjectileScript), 9),
        (nameof(ArrowBallAllDirections75R2ProjectileScript), 9),
        (nameof(PlasmaBallAllDirections75R2ProjectileScript), 9),
        (nameof(HolyFireBallAllDirections75R2ProjectileScript), 9),
        (nameof(WaterBallAllDirections75R2ProjectileScript), 9),
        (nameof(LightBallAllDirections75R2ProjectileScript), 9),
        (nameof(DarknessBallAllDirections75R2ProjectileScript), 9),
        (nameof(ForceBallAllDirections75R2ProjectileScript), 9),
        (nameof(InertiaBallAllDirections75R2ProjectileScript), 9),
        (nameof(ManaBallAllDirections75R2ProjectileScript), 9),
        (nameof(MeteorBallAllDirections75R2ProjectileScript), 9),
        (nameof(IceBallAllDirections75R2ProjectileScript), 9),
        (nameof(ChaosBallAllDirections75R2ProjectileScript), 9),
        (nameof(NetherBallAllDirections75R2ProjectileScript), 9),
        (nameof(DisenchantBallAllDirections75R2ProjectileScript), 9),
        (nameof(ExplodeBallAllDirections75R2ProjectileScript), 9),
        (nameof(SoundBallAllDirections75R2ProjectileScript), 9),
        (nameof(NexusBallAllDirections75R2ProjectileScript), 9),
        (nameof(ConfusionBallAllDirections75R2ProjectileScript), 9),
        (nameof(TimeBallAllDirections75R2ProjectileScript), 9),
        (nameof(GravityBallAllDirections75R2ProjectileScript), 9),
        (nameof(ShardBallAllDirections75R2ProjectileScript), 9),
        (nameof(NukeBallAllDirections75R2ProjectileScript), 9),
        (nameof(HellfireBallAllDirections75R2ProjectileScript), 9),
        (nameof(DisintegrateBallAllDirections75R2ProjectileScript), 9),

        (nameof(ElectricityBallAtSelf800R8ProjectileScript), 24),
        (nameof(PoisonGasBallAtSelf800R8ProjectileScript), 24),
        (nameof(AcidBallAtSelf800R8ProjectileScript), 24),
        (nameof(ColdBallAtSelf800R8ProjectileScript), 24),
        (nameof(FireBallAtSelf800R8ProjectileScript), 24),
        (nameof(MissileBallAtSelf800R8ProjectileScript), 24),
        (nameof(ArrowBallAtSelf800R8ProjectileScript), 24),
        (nameof(PlasmaBallAtSelf800R8ProjectileScript), 24),
        (nameof(HolyFireBallAtSelf800R8ProjectileScript), 24),
        (nameof(WaterBallAtSelf800R8ProjectileScript), 24),
        (nameof(LightBallAtSelf800R8ProjectileScript), 24),
        (nameof(DarknessBallAtSelf800R8ProjectileScript), 24),
        (nameof(ForceBallAtSelf800R8ProjectileScript), 24),
        (nameof(InertiaBallAtSelf800R8ProjectileScript), 24),
        (nameof(ManaBallAtSelf800R8ProjectileScript), 24),
        (nameof(MeteorBallAtSelf800R8ProjectileScript), 24),
        (nameof(IceBallAtSelf800R8ProjectileScript), 24),
        (nameof(ChaosBallAtSelf800R8ProjectileScript), 24),
        (nameof(NetherBallAtSelf800R8ProjectileScript), 24),
        (nameof(DisenchantBallAtSelf800R8ProjectileScript), 24),
        (nameof(ExplodeBallAtSelf800R8ProjectileScript), 24),
        (nameof(SoundBallAtSelf800R8ProjectileScript), 24),
        (nameof(NexusBallAtSelf800R8ProjectileScript), 24),
        (nameof(ConfusionBallAtSelf800R8ProjectileScript), 24),
        (nameof(TimeBallAtSelf800R8ProjectileScript), 24),
        (nameof(GravityBallAtSelf800R8ProjectileScript), 24),
        (nameof(ShardBallAtSelf800R8ProjectileScript), 24),
        (nameof(NukeBallAtSelf800R8ProjectileScript), 24),
        (nameof(HellfireBallAtSelf800R8ProjectileScript), 24),
        (nameof(DisintegrateBallAtSelf800R8ProjectileScript), 24),

        (nameof(ElectricityBeam150R3PXO35ProjectileScript), 12),
        (nameof(PoisonGasBeam150R3PXO35ProjectileScript), 12),
        (nameof(AcidBeam150R3PXO35ProjectileScript), 12),
        (nameof(ColdBeam150R3PXO35ProjectileScript), 12),
        (nameof(FireBeam150R3PXO35ProjectileScript), 12),
        (nameof(MissileBeam150R3PXO35ProjectileScript), 12),
        (nameof(ArrowBeam150R3PXO35ProjectileScript), 12),
        (nameof(PlasmaBeam150R3PXO35ProjectileScript), 12),
        (nameof(HolyFireBeam150R3PXO35ProjectileScript), 12),
        (nameof(WaterBeam150R3PXO35ProjectileScript), 12),
        (nameof(LightBeam150R3PXO35ProjectileScript), 12),
        (nameof(DarknessBeam150R3PXO35ProjectileScript), 12),
        (nameof(ForceBeam150R3PXO35ProjectileScript), 12),
        (nameof(InertiaBeam150R3PXO35ProjectileScript), 12),
        (nameof(ManaBeam150R3PXO35ProjectileScript), 12),
        (nameof(MeteorBeam150R3PXO35ProjectileScript), 12),
        (nameof(IceBeam150R3PXO35ProjectileScript), 12),
        (nameof(ChaosBeam150R3PXO35ProjectileScript), 12),
        (nameof(NetherBeam150R3PXO35ProjectileScript), 12),
        (nameof(DisenchantBeam150R3PXO35ProjectileScript), 12),
        (nameof(ExplodeBeam150R3PXO35ProjectileScript), 12),
        (nameof(SoundBeam150R3PXO35ProjectileScript), 12),
        (nameof(NexusBeam150R3PXO35ProjectileScript), 12),
        (nameof(ConfusionBeam150R3PXO35ProjectileScript), 12),
        (nameof(TimeBeam150R3PXO35ProjectileScript), 12),
        (nameof(GravityBeam150R3PXO35ProjectileScript), 12),
        (nameof(ShardBeam150R3PXO35ProjectileScript), 12),
        (nameof(NukeBeam150R3PXO35ProjectileScript), 12),
        (nameof(HellfireBeam150R3PXO35ProjectileScript), 12),
        (nameof(DisintegrateBeam150R3PXO35ProjectileScript), 12),

        (nameof(ElectricityBall150R3PXO35ProjectileScript), 24),
        (nameof(PoisonGasBall150R3PXO35ProjectileScript), 24),
        (nameof(AcidBall150R3PXO35ProjectileScript), 24),
        (nameof(ColdBall150R3PXO35ProjectileScript), 24),
        (nameof(FireBall150R3PXO35ProjectileScript), 24),
        (nameof(MissileBall150R3PXO35ProjectileScript), 24),
        (nameof(ArrowBall150R3PXO35ProjectileScript), 24),
        (nameof(PlasmaBall150R3PXO35ProjectileScript), 24),
        (nameof(HolyFireBall150R3PXO35ProjectileScript), 24),
        (nameof(WaterBall150R3PXO35ProjectileScript), 24),
        (nameof(LightBall150R3PXO35ProjectileScript), 24),
        (nameof(DarknessBall150R3PXO35ProjectileScript), 24),
        (nameof(ForceBall150R3PXO35ProjectileScript), 24),
        (nameof(InertiaBall150R3PXO35ProjectileScript), 24),
        (nameof(ManaBall150R3PXO35ProjectileScript), 24),
        (nameof(MeteorBall150R3PXO35ProjectileScript), 24),
        (nameof(IceBall150R3PXO35ProjectileScript), 24),
        (nameof(ChaosBall150R3PXO35ProjectileScript), 24),
        (nameof(NetherBall150R3PXO35ProjectileScript), 24),
        (nameof(DisenchantBall150R3PXO35ProjectileScript), 24),
        (nameof(ExplodeBall150R3PXO35ProjectileScript), 24),
        (nameof(SoundBall150R3PXO35ProjectileScript), 24),
        (nameof(NexusBall150R3PXO35ProjectileScript), 24),
        (nameof(ConfusionBall150R3PXO35ProjectileScript), 24),
        (nameof(TimeBall150R3PXO35ProjectileScript), 24),
        (nameof(GravityBall150R3PXO35ProjectileScript), 24),
        (nameof(ShardBall150R3PXO35ProjectileScript), 24),
        (nameof(NukeBall150R3PXO35ProjectileScript), 24),
        (nameof(HellfireBall150R3PXO35ProjectileScript), 24),
        (nameof(DisintegrateBall150R3PXO35ProjectileScript), 24),
    };
    public override string LearnedDetails => "dam 75 / 150";
}
