// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class ClassSpellMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("SpellName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Spell Name",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("CharacterClassName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Character Class Name",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("Level")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Level",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("ManaCost")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Mana Cost",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("BaseFailure")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Base Failure",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("FirstCastExperience")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "First Cast Experience",
                    CategoryTitle = "",
                },
            };
        }
    }
}
