// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class DungeonGuardianMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                    CategoryTitle = "",
                },
                new ForeignKeyPropertyMetadata("MonsterRaceName")
                {
                    ForeignCollectionName = "MonsterRaces",
                    Description = "Returns the name of the race for the first quest monster.",
                    IsNullable = false,
                    Title = "Monster Race Name",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("LevelFound")
                {
                    DefaultValue = null,
                    Description = "The level for the fixed quest.",
                    IsNullable = false,
                    Title = "Level Found",
                    CategoryTitle = "",
                },
            };
        }
    }
}
