// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class GameConfigurationMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new IntegerPropertyMetadata("MaxMessageLogLength")
                {
                    DefaultValue = 2048,
                    Description = "Returns the number of log items that the message history is allowed to store.  A null value indicates that there is no limit.  The default value is 2048.",
                    IsNullable = true,
                    Title = "Max Message Log Length",
                },
                new StringPropertyMetadata("StartupTownName")
                {
                    DefaultValue = null,
                    Description = "Returns the name of the town where the player will start, ignoring whether or not that town is a startup town; or null, for a random town to be choosen from the available startup towns.",
                    IsNullable = true,
                    Title = "Startup Town Name",
                },
                new CollectionPropertyMetadata("Towns")
                {
                    PropertyMetadatas = TownMetadata.Metadata,
                    EntityTitle = "Town",
                    KeyPropertyName = "Key",
                    Description = "Returns null, if Towns should be loaded from the assembly.  Otherwise, returns an array of Towns to be loaded into the SingletonRepository.",
                    IsNullable = true,
                    Title = "Towns",
                },
                new CollectionPropertyMetadata("Shopkeepers")
                {
                    PropertyMetadatas = ShopkeeperMetadata.Metadata,
                    EntityTitle = "Shopkeeper",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeepers",
                },
                new CollectionPropertyMetadata("GameCommands")
                {
                    PropertyMetadatas = GameCommandMetadata.Metadata,
                    EntityTitle = "GameCommand",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Game Commands",
                },
                new CollectionPropertyMetadata("StoreCommands")
                {
                    PropertyMetadatas = StoreCommandMetadata.Metadata,
                    EntityTitle = "StoreCommand",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Store Commands",
                },
                new CollectionPropertyMetadata("HelpGroups")
                {
                    PropertyMetadatas = HelpGroupMetadata.Metadata,
                    EntityTitle = "HelpGroup",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Help Groups",
                },
                new CollectionPropertyMetadata("MonsterRaces")
                {
                    PropertyMetadatas = MonsterRaceMetadata.Metadata,
                    EntityTitle = "MonsterRace",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Monster Races",
                },
                new CollectionPropertyMetadata("Symbols")
                {
                    PropertyMetadatas = SymbolMetadata.Metadata,
                    EntityTitle = "Symbol",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Symbols",
                },
                new CollectionPropertyMetadata("Vaults")
                {
                    PropertyMetadatas = VaultMetadata.Metadata,
                    EntityTitle = "Vault",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Vaults",
                },
                new CollectionPropertyMetadata("DungeonGuardians")
                {
                    PropertyMetadatas = DungeonGuardianMetadata.Metadata,
                    EntityTitle = "DungeonGuardian",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Dungeon Guardians",
                },
                new CollectionPropertyMetadata("Dungeons")
                {
                    PropertyMetadatas = DungeonMetadata.Metadata,
                    EntityTitle = "Dungeon",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Dungeons",
                },
                new CollectionPropertyMetadata("StoreFactories")
                {
                    PropertyMetadatas = StoreFactoryMetadata.Metadata,
                    EntityTitle = "StoreFactory",
                    KeyPropertyName = "Key",
                    Description = "Towns have various plots where buildings and/or stores may be placed.  Stores factories are used to create specific stores.  Store factories can produce more than one store per town.  Use this collection to define factories that are used to create stores.",
                    IsNullable = true,
                    Title = "Store Factories",
                },
                new CollectionPropertyMetadata("ProjectileGraphics")
                {
                    PropertyMetadatas = ProjectileGraphicMetadata.Metadata,
                    EntityTitle = "ProjectileGraphic",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Projectile Graphics",
                },
                new CollectionPropertyMetadata("AmuletReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Amulet Readable Flavors",
                },
                new CollectionPropertyMetadata("MushroomReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Mushroom Readable Flavors",
                },
                new CollectionPropertyMetadata("PotionReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Potion Readable Flavors",
                },
                new CollectionPropertyMetadata("RingReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Ring Readable Flavors",
                },
                new CollectionPropertyMetadata("RodReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Rod Readable Flavors",
                },
                new CollectionPropertyMetadata("ScrollReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Scroll Readable Flavors",
                },
                new CollectionPropertyMetadata("StaffReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Staff Readable Flavors",
                },
                new CollectionPropertyMetadata("WandReadableFlavors")
                {
                    PropertyMetadatas = ReadableFlavorMetadata.Metadata,
                    EntityTitle = "ReadableFlavor",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Wand Readable Flavors",
                },
                new CollectionPropertyMetadata("ClassSpells")
                {
                    PropertyMetadatas = ClassSpellMetadata.Metadata,
                    EntityTitle = "ClassSpell",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Class Spells",
                },
                new CollectionPropertyMetadata("WizardCommands")
                {
                    PropertyMetadatas = WizardCommandMetadata.Metadata,
                    EntityTitle = "WizardCommand",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Wizard Commands",
                },
                new CollectionPropertyMetadata("Tiles")
                {
                    PropertyMetadatas = TileMetadata.Metadata,
                    EntityTitle = "Tile",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Tiles",
                },
                new CollectionPropertyMetadata("Animations")
                {
                    PropertyMetadatas = AnimationMetadata.Metadata,
                    EntityTitle = "Animation",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Animations",
                },
                new CollectionPropertyMetadata("Spells")
                {
                    PropertyMetadatas = SpellMetadata.Metadata,
                    EntityTitle = "Spell",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Spells",
                },
                new CollectionPropertyMetadata("Plurals")
                {
                    PropertyMetadatas = PluralMetadata.Metadata,
                    EntityTitle = "Plural",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Plurals",
                },
                new CollectionPropertyMetadata("Attacks")
                {
                    PropertyMetadatas = AttackMetadata.Metadata,
                    EntityTitle = "Attack",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Attacks",
                },
                new CollectionPropertyMetadata("Gods")
                {
                    PropertyMetadatas = GodMetadata.Metadata,
                    EntityTitle = "God",
                    KeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Gods",
                },
                new StringsPropertyMetadata("ElvishTexts")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Elvish Texts",
                },
                new StringsPropertyMetadata("FindQuests")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Find Quests",
                },
                new StringsPropertyMetadata("FunnyComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Funny Comments",
                },
                new StringsPropertyMetadata("FunnyDescriptions")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Funny Descriptions",
                },
                new StringsPropertyMetadata("HorrificDescriptions")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Horrific Descriptions",
                },
                new StringsPropertyMetadata("InsultPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Insult Player Attacks",
                },
                new StringsPropertyMetadata("MoanPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Moan Player Attacks",
                },
                new StringsPropertyMetadata("UnreadableFlavorSyllables")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Unreadable Flavor Syllables",
                },
                new StringsPropertyMetadata("ShopkeeperAcceptedComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Accepted Comments",
                },
                new StringsPropertyMetadata("ShopkeeperBargainComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Bargain Comments",
                },
                new StringsPropertyMetadata("ShopkeeperGoodComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Good Comments",
                },
                new StringsPropertyMetadata("ShopkeeperLessThanGuessComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Less Than Guess Comments",
                },
                new StringsPropertyMetadata("ShopkeeperWorthlessComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Worthless Comments",
                },
                new StringsPropertyMetadata("SingingPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Singing Player Attacks",
                },
                new StringsPropertyMetadata("WorshipPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Worship Player Attacks",
                },
            };
        }
    }
}
