// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class GameConfigurationMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new IntegerPropertyMetadata("MaxMessageLogLength")
                {
                    DefaultValue = 2048,
                    Description = "Returns the number of log items that the message history is allowed to store.  A null value indicates that there is no limit.  The default value is 2048.",
                    IsNullable = true,
                    Title = "Max Message Log Length",
                },
                new StringPropertyMetadata("StartupTownName")
                {
                    DefaultValue = null,
                    Description = "Returns the name of the town where the player will start, ignoring whether or not that town is a startup town; or null, for a random town to be choosen from the available startup towns.",
                    IsNullable = true,
                    Title = "Startup Town Name",
                },
                new CollectionPropertyMetadata("Towns")
                {
                    PropertyMetadatas = TownMetadata.Metadata,
                    EntityTitle = "Town",
                    EntityName = "Town",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "Returns null, if Towns should be loaded from the assembly.  Otherwise, returns an array of Towns to be loaded into the SingletonRepository.",
                    IsNullable = true,
                    Title = "Towns",
                },
                new CollectionPropertyMetadata("Shopkeepers")
                {
                    PropertyMetadatas = ShopkeeperMetadata.Metadata,
                    EntityTitle = "Shopkeeper",
                    EntityName = "Shopkeeper",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeepers",
                },
                new CollectionPropertyMetadata("GameCommands")
                {
                    PropertyMetadatas = GameCommandMetadata.Metadata,
                    EntityTitle = "Game Command",
                    EntityName = "GameCommand",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Game Commands",
                },
                new CollectionPropertyMetadata("StoreCommands")
                {
                    PropertyMetadatas = StoreCommandMetadata.Metadata,
                    EntityTitle = "Store Command",
                    EntityName = "StoreCommand",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Store Commands",
                },
                new CollectionPropertyMetadata("HelpGroups")
                {
                    PropertyMetadatas = HelpGroupMetadata.Metadata,
                    EntityTitle = "Help Group",
                    EntityName = "HelpGroup",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Help Groups",
                },
                new CollectionPropertyMetadata("MonsterRaces")
                {
                    PropertyMetadatas = MonsterRaceMetadata.Metadata,
                    EntityTitle = "Monster Race",
                    EntityName = "MonsterRace",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Monster Races",
                },
                new CollectionPropertyMetadata("Symbols")
                {
                    PropertyMetadatas = SymbolMetadata.Metadata,
                    EntityTitle = "Symbol",
                    EntityName = "Symbol",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Symbols",
                },
                new CollectionPropertyMetadata("Vaults")
                {
                    PropertyMetadatas = VaultMetadata.Metadata,
                    EntityTitle = "Vault",
                    EntityName = "Vault",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Vaults",
                },
                new CollectionPropertyMetadata("DungeonGuardians")
                {
                    PropertyMetadatas = DungeonGuardianMetadata.Metadata,
                    EntityTitle = "Dungeon Guardian",
                    EntityName = "DungeonGuardian",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Dungeon Guardians",
                },
                new CollectionPropertyMetadata("Dungeons")
                {
                    PropertyMetadatas = DungeonMetadata.Metadata,
                    EntityTitle = "Dungeon",
                    EntityName = "Dungeon",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Dungeons",
                },
                new CollectionPropertyMetadata("StoreFactories")
                {
                    PropertyMetadatas = StoreFactoryMetadata.Metadata,
                    EntityTitle = "Store Factory",
                    EntityName = "StoreFactory",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "Towns have various plots where buildings and/or stores may be placed.  Stores factories are used to create specific stores.  Store factories can produce more than one store per town.  Use this collection to define factories that are used to create stores.",
                    IsNullable = true,
                    Title = "Store Factories",
                },
                new CollectionPropertyMetadata("ProjectileGraphics")
                {
                    PropertyMetadatas = ProjectileGraphicMetadata.Metadata,
                    EntityTitle = "Projectile Graphic",
                    EntityName = "ProjectileGraphic",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Projectile Graphics",
                },
                new CollectionPropertyMetadata("AmuletReadableFlavors")
                {
                    PropertyMetadatas = AmuletReadableFlavorMetadata.Metadata,
                    EntityTitle = "Amulet Readable Flavor",
                    EntityName = "AmuletReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Amulet Readable Flavors",
                },
                new CollectionPropertyMetadata("MushroomReadableFlavors")
                {
                    PropertyMetadatas = MushroomReadableFlavorMetadata.Metadata,
                    EntityTitle = "Mushroom Readable Flavor",
                    EntityName = "MushroomReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Mushroom Readable Flavors",
                },
                new CollectionPropertyMetadata("PotionReadableFlavors")
                {
                    PropertyMetadatas = PotionReadableFlavorMetadata.Metadata,
                    EntityTitle = "Potion Readable Flavor",
                    EntityName = "PotionReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Potion Readable Flavors",
                },
                new CollectionPropertyMetadata("RingReadableFlavors")
                {
                    PropertyMetadatas = RingReadableFlavorMetadata.Metadata,
                    EntityTitle = "Ring Readable Flavor",
                    EntityName = "RingReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Ring Readable Flavors",
                },
                new CollectionPropertyMetadata("RodReadableFlavors")
                {
                    PropertyMetadatas = RodReadableFlavorMetadata.Metadata,
                    EntityTitle = "Rod Readable Flavor",
                    EntityName = "RodReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Rod Readable Flavors",
                },
                new CollectionPropertyMetadata("ScrollReadableFlavors")
                {
                    PropertyMetadatas = ScrollReadableFlavorMetadata.Metadata,
                    EntityTitle = "Scroll Readable Flavor",
                    EntityName = "ScrollReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Scroll Readable Flavors",
                },
                new CollectionPropertyMetadata("StaffReadableFlavors")
                {
                    PropertyMetadatas = StaffReadableFlavorMetadata.Metadata,
                    EntityTitle = "Staff Readable Flavor",
                    EntityName = "StaffReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Staff Readable Flavors",
                },
                new CollectionPropertyMetadata("WandReadableFlavors")
                {
                    PropertyMetadatas = WandReadableFlavorMetadata.Metadata,
                    EntityTitle = "Wand Readable Flavor",
                    EntityName = "WandReadableFlavor",
                    EntityNamePropertyName = "Name",
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Wand Readable Flavors",
                },
                new CollectionPropertyMetadata("ClassSpells")
                {
                    PropertyMetadatas = ClassSpellMetadata.Metadata,
                    EntityTitle = "Class Spell",
                    EntityName = "ClassSpell",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Class Spells",
                },
                new CollectionPropertyMetadata("WizardCommands")
                {
                    PropertyMetadatas = WizardCommandMetadata.Metadata,
                    EntityTitle = "Wizard Command",
                    EntityName = "WizardCommand",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Wizard Commands",
                },
                new CollectionPropertyMetadata("Tiles")
                {
                    PropertyMetadatas = TileMetadata.Metadata,
                    EntityTitle = "Tile",
                    EntityName = "Tile",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Tiles",
                },
                new CollectionPropertyMetadata("Animations")
                {
                    PropertyMetadatas = AnimationMetadata.Metadata,
                    EntityTitle = "Animation",
                    EntityName = "Animation",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Animations",
                },
                new CollectionPropertyMetadata("Spells")
                {
                    PropertyMetadatas = SpellMetadata.Metadata,
                    EntityTitle = "Spell",
                    EntityName = "Spell",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Spells",
                },
                new CollectionPropertyMetadata("Plurals")
                {
                    PropertyMetadatas = PluralMetadata.Metadata,
                    EntityTitle = "Plural",
                    EntityName = "Plural",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Plurals",
                },
                new CollectionPropertyMetadata("Attacks")
                {
                    PropertyMetadatas = AttackMetadata.Metadata,
                    EntityTitle = "Attack",
                    EntityName = "Attack",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Attacks",
                },
                new CollectionPropertyMetadata("Gods")
                {
                    PropertyMetadatas = GodMetadata.Metadata,
                    EntityTitle = "God",
                    EntityName = "God",
                    EntityNamePropertyName = null,
                    EntityKeyPropertyName = "Key",
                    Description = "",
                    IsNullable = true,
                    Title = "Gods",
                },
                new StringsPropertyMetadata("ElvishTexts")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Elvish Texts",
                },
                new StringsPropertyMetadata("FindQuests")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Find Quests",
                },
                new StringsPropertyMetadata("FunnyComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Funny Comments",
                },
                new StringsPropertyMetadata("FunnyDescriptions")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Funny Descriptions",
                },
                new StringsPropertyMetadata("HorrificDescriptions")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Horrific Descriptions",
                },
                new StringsPropertyMetadata("InsultPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Insult Player Attacks",
                },
                new StringsPropertyMetadata("MoanPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Moan Player Attacks",
                },
                new StringsPropertyMetadata("UnreadableFlavorSyllables")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Unreadable Flavor Syllables",
                },
                new StringsPropertyMetadata("ShopkeeperAcceptedComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Accepted Comments",
                },
                new StringsPropertyMetadata("ShopkeeperBargainComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Bargain Comments",
                },
                new StringsPropertyMetadata("ShopkeeperGoodComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Good Comments",
                },
                new StringsPropertyMetadata("ShopkeeperLessThanGuessComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Less Than Guess Comments",
                },
                new StringsPropertyMetadata("ShopkeeperWorthlessComments")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Shopkeeper Worthless Comments",
                },
                new StringsPropertyMetadata("SingingPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Singing Player Attacks",
                },
                new StringsPropertyMetadata("WorshipPlayerAttacks")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Worship Player Attacks",
                },
            };
        }
    }
}
