// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class GodMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("LongName")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Long Name",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("ShortName")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Short Name",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("FavorDescription")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Favor Description",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("Key")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                    CategoryTitle = "",
                },
            };
        }
    }
}
