// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class HelpGroupMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                },
                new IntegerPropertyMetadata("SortIndex")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Sort Index",
                },
                new StringPropertyMetadata("Title")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Title",
                },
            };
        }
    }
}
