// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class PluralMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "Returns the capitalized singular version of the noun.",
                    IsNullable = false,
                    Title = "Key",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("PluralForm")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "Returns the pluralized version of the key. the class.",
                    IsNullable = false,
                    Title = "Plural Form",
                    CategoryTitle = "",
                },
            };
        }
    }
}
