// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class RingReadableFlavorMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                },
                new StringPropertyMetadata("SymbolName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Symbol Name",
                },
                new ColorPropertyMetadata("Color")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Color",
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Name",
                },
                new BooleanPropertyMetadata("CanBeAssigned")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Can Be Assigned",
                },
            };
        }
    }
}
