// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class ShopkeeperMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("MaxCost")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Max Cost",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("MinInflate")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Min Inflate",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Name",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("RaceName")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Race Name",
                    CategoryTitle = "",
                },
            };
        }
    }
}
