// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class SymbolMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new CharacterPropertyMetadata("Character")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Character",
                },
                new CharacterPropertyMetadata("QueryCharacter")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = true,
                    Title = "Query Character",
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Name",
                },
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                },
            };
        }
    }
}
