// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class TownMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                    CategoryTitle = "",
                },
                new CharacterPropertyMetadata("Char")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Char",
                    CategoryTitle = "",
                },
                new IntegerPropertyMetadata("HousePrice")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "House Price",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("Name")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Name",
                    CategoryTitle = "",
                },
                new StringsPropertyMetadata("StoreFactoryNames")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Store Factory Names",
                    CategoryTitle = "",
                },
                new BooleanPropertyMetadata("CanBeEscortedHere")
                {
                    DefaultValue = true,
                    Description = "",
                    IsNullable = false,
                    Title = "Can Be Escorted Here",
                    CategoryTitle = "",
                },
                new BooleanPropertyMetadata("AllowStartupTown")
                {
                    DefaultValue = true,
                    Description = "",
                    IsNullable = false,
                    Title = "Allow Startup Town",
                    CategoryTitle = "",
                },
                new StringPropertyMetadata("DungeonName")
                {
                    DefaulDefaultValuetValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Dungeon Name",
                    CategoryTitle = "",
                },
                new BooleanPropertyMetadata("UnusedStoreLotsAreGraveyards")
                {
                    DefaultValue = false,
                    Description = "",
                    IsNullable = false,
                    Title = "Unused Store Lots Are Graveyards",
                    CategoryTitle = "",
                },
            };
        }
    }
}
