// <auto-generated>
// This code was generated by scaffold-metadata.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
namespace AngbandOS.Core.Interface.Metadata;

public static class VaultMetadata
{
    public static PropertyMetadata[] Metadata
    {
        get
        {
            return new PropertyMetadata[]
            {
                new StringPropertyMetadata("Key")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Key",
                },
                new ColorPropertyMetadata("Color")
                {
                    DefaultValue = ColorEnum.White,
                    Description = "",
                    IsNullable = false,
                    Title = "Color",
                },
                new StringPropertyMetadata("Name")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Name",
                },
                new IntegerPropertyMetadata("Category")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Category",
                },
                new IntegerPropertyMetadata("Height")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Height",
                },
                new IntegerPropertyMetadata("Rating")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Rating",
                },
                new StringPropertyMetadata("Text")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Text",
                },
                new IntegerPropertyMetadata("Width")
                {
                    DefaultValue = null,
                    Description = "",
                    IsNullable = false,
                    Title = "Width",
                },
            };
        }
    }
}
