// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”

namespace AngbandOS.GamePacks.Cthangband;

public class CthangbandGameConfiguration : GameConfiguration
{
    public override string[]? GoldFactoriesBindingKeys => new string[]
    {
        "CopperGoldItemFactory",
        "Copper1GoldItemFactory",
        "Copper2GoldItemFactory",
        "PieceOfSilverGoldItemFactory",
        "Silver1GoldItemFactory",
        "Silver2GoldItemFactory",
        "SomeGarnetsGoldItemFactory",
        "LotOfGarnetsGoldItemFactory",
        "GoldGoldItemFactory",
        "SomeGoldGoldItemFactory",
        "LotOfGoldGoldItemFactory",
        "OpalsGoldItemFactory",
        "SapphiresGoldItemFactory",
        "RubiesGoldItemFactory",
        "DiamondsGoldItemFactory",
        "EmeraldsGoldItemFactory",
        "MithrilGoldItemFactory",
        "AdamantiteGoldItemFactory"
    };

    public override HelpGroupGameConfiguration[]? HelpGroups => new HelpGroupGameConfiguration[]
    {
        new WizardCharacterEditingHelpGroup(),
        new WizardGeneralCommandsHelpGroup(),
        new WizardMonstersHelpGroup(),
        new WizardMovementHelpGroup(),
        new WizardObjectCommandsHelpGroup()
    };

    public override SymbolGameConfiguration[]? Symbols => new SymbolGameConfiguration[]
    {
        new AmpersandSymbol(),
        new AsteriskSymbol(),
        new AtSymbol(),
        new BackSlashSymbol(),
        new CaretSymbol(),
        new CloseBraceSymbol(),
        new CloseBracketSymbol(),
        new CloseParenthesisSymbol(),
        new ColonSymbol(),
        new CommaSymbol(),
        new DollarSignSymbol(),
        new DoubleQuoteSymbol(),
        new EqualSignSymbol(),
        new ExclamationPointSymbol(),
        new ForwardSlashSymbol(),
        new GreaterThanSymbol(),
        new LessThanSymbol(),
        new LowerASymbol(),
        new LowerBSymbol(),
        new LowerCSymbol(),
        new LowerDSymbol(),
        new LowerESymbol(),
        new LowerFSymbol(),
        new LowerGSymbol(),
        new LowerHSymbol(),
        new LowerISymbol(),
        new LowerJSymbol(),
        new LowerKSymbol(),
        new LowerLSymbol(),
        new LowerMSymbol(),
        new LowerNSymbol(),
        new LowerOSymbol(),
        new LowerPSymbol(),
        new LowerQSymbol(),
        new LowerRSymbol(),
        new LowerSSymbol(),
        new LowerTSymbol(),
        new LowerUSymbol(),
        new LowerVSymbol(),
        new LowerWSymbol(),
        new LowerXSymbol(),
        new LowerYSymbol(),
        new LowerZSymbol(),
        new LowerASymbol(),
        new MinusSignSymbol(),
        new NumberEightSymbol(),
        new NumberFiveSymbol(),
        new NumberFourSymbol(),
        new NumberNineSymbol(),
        new NumberOneSymbol(),
        new NumberSevenSymbol(),
        new NumberSixSymbol(),
        new NumberThreeSymbol(),
        new NumberTwoSymbol(),
        new NumberZeroSymbol(),
        new OpenBraceSymbol(),
        new OpenBracketSymbol(),
        new OpenParenthesisSymbol(),
        new PercentSignSymbol(),
        new PeriodSymbol(),
        new PlusSignSymbol(),
        new PoundSignSymbol(),
        new QuestionMarkSymbol(),
        new SemiColonSymbol(),
        new SingleQuoteSymbol(),
        new SpaceBarSymbol(),
        new TildeSymbol(),
        new UnderscoreSymbol(),
        new UpperASymbol(),
        new UpperBSymbol(),
        new UpperCSymbol(),
        new UpperDSymbol(),
        new UpperESymbol(),
        new UpperFSymbol(),
        new UpperGSymbol(),
        new UpperHSymbol(),
        new UpperISymbol(),
        new UpperJSymbol(),
        new UpperKSymbol(),
        new UpperLSymbol(),
        new UpperMSymbol(),
        new UpperOSymbol(),
        new UpperPSymbol(),
        new UpperQSymbol(),
        new UpperRSymbol(),
        new UpperSSymbol(),
        new UpperTSymbol(),
        new UpperUSymbol(),
        new UpperVSymbol(),
        new UpperWSymbol(),
        new UpperXSymbol(),
        new UpperYSymbol(),
        new UpperZSymbol(),
        new VerticalBarSymbol()
    };
}
