// Cthangband: © 1997 - 2022 Dean Anderson, Based on Angband: © 1997 Ben Harrison, James E. Wilson,
// Robert A. Koeneke, Based on Moria: © 1985 Robert Alan Koeneke and Umoria: © 1989 James E.Wilson
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”
namespace AngbandOS.Core;

internal enum PotionType // TODO: Cannot be removed until initial items given to player are resolved.
{
    AppleJuice = 1, // This is always light brown flavour color
    Augmentation = 55,
    BeserkStrength = 33,
    Blindness = 7,
    Boldness = 28,
    Confusion = 9,
    CureCritical = 36,
    CureLight = 34,
    CurePoison = 27,
    CureSerious = 35,
    Curing = 61,
    Death = 23,
    DecCha = 21,
    DecCon = 20,
    DecDex = 19,
    DecInt = 17,
    DecStr = 16,
    DecWis = 18,
    DetectInvis = 25,
    Detonations = 22,
    Enlightenment = 56,
    Experience = 59,
    Healing = 37,
    Heroism = 32,
    IncCha = 53,
    IncCon = 52,
    IncDex = 51,
    IncInt = 49,
    IncStr = 48,
    IncWis = 50,
    Infravision = 24,
    Invulnerability = 62,
    Life = 39,
    LoseMemories = 13,
    NewLife = 63,
    Poison = 6,
    ResCha = 47,
    ResCon = 46,
    ResDex = 45,
    ResInt = 43,
    Resistance = 60,
    ResistCold = 31,
    ResistHeat = 30,
    ResStr = 42,
    RestoreExp = 41,
    RestoreMana = 40,
    ResWis = 44,
    Ruination = 15,
    SaltWater = 5,
    SelfKnowledge = 58,
    Sleep = 11,
    SlimeMold = 2, // This is always light green flavour
    Slowness = 4,
    SlowPoison = 26,
    Speed = 29,
    StarEnlightenment = 57,
    StarHealing = 38,
    Water = 0 // This is always clear flavour
}