// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”

namespace AngbandOS.Core.Interface.Configuration;

public enum ItemFiltersEnum
{
    AllItemsItemFilter,
    AmuletsOfValueItemFilter,
    AnythingOfValueItemFilter,
    ArmorItemFilter,
    ArrowsOfValueItemFilter,
    BlessedPolearmsOfValueItemFilter,
    BlessedSwordsOfValueItemFilter,
    BoltsItemFilter,
    BoltsOfValueItemFilter,
    BootsOfValueItemFilter,
    BottlesOfValueItemFilter,
    BowsOfValueItemFilter,
    CanBeAimedItemFilter,
    CanBeEatenItemFilter,
    CanBeFiredItemFilter,
    CanBeQuaffedItemFilter,
    CanBeReadItemFilter,
    CanBeRechargedItemFilter,
    CanBeUsedItemFilter,
    CanBeWornOrWieldedItemFilter,
    CanBeZappedItemFilter,
    ChaosSpellBooksOfValueItemFilter,
    CloaksOfValueItemFilter,
    CorporealSpellBooksOfValueItemFilter,
    CrownsOfValueItemFilter,
    DeathSpellBooksOfValueItemFilter,
    DiggersOfValueItemFilter,
    DragonScaleMailOfValueItemFilter,
    FlasksOfValueItemFilter,
    FolkSpellBooksOfValueItemFilter,
    FoodOfValueItemFilter,
    GlovesOfValueItemFilter,
    HaftedWeaponsOfValueItemFilter,
    HardArmorOfValueItemFilter,
    HelmsOfValueItemFilter,
    IsHighLevelSpellBookItemFilter,
    IsUnusableHighLevelSpellBookItemFilter,
    IsUsableSpellBookItemFilter,
    KnownAndActivableItemFilter,
    LanternFuelItemFilter,
    LifeBooksOfValueItemFilter,
    LightSourcesOfValueItemFilter,
    NatureSpellBooksOfValueItemFilter,
    PolearmsOfValueItemFilter,
    PotionsOfValueItemFilter,
    RingsOfValueItemFilter,
    RodsOfValueItemFilter,
    ScrollsOfValueItemFilter,
    ShieldsOfValueItemFilter,
    ShotsOfValueItemFilter,
    SoftArmorOfValueItemFilter,
    SorcerySpellBooksOfValueItemFilter,
    SpikeOfValueItemFilter,
    StaffsOfValueItemFilter,
    SwordsOfValueItemFilter,
    TarotSpellBooksOfValueItemFilter,
    TorchFuelItemFilter,
    WandsOfValueItemFilter,
    WeaponsItemFilter,
}
