// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”

namespace AngbandOS.Core.Interface.Configuration;

public enum MonsterEffectScriptsEnum
{
    AcidMonsterEffect,
    ArrowMonsterEffect,
    ChaosMonsterEffect,
    CharmMonsterEffect,
    ColdMonsterEffect,
    ConfusionMonsterEffect,
    ControlAnimalMonsterEffect,
    ControlUndeadMonsterEffect,
    DarknessMonsterEffect,
    DarknessWeakMonsterEffect,
    DeathRayMonsterEffect,
    DestroyTrapOrDoorMonsterEffect,
    DisenchantMonsterEffect,
    DisintegrateMonsterEffect,
    DispelAllMonsterEffect,
    DispelDemonMonsterEffect,
    DispelEvilMonsterEffect,
    DispelGoodMonsterEffect,
    DispelLivingMonsterEffect,
    DispelUndeadMonsterEffect,
    DominationMonsterEffect,
    ElectricityMonsterEffect,
    ExplodeMonsterEffect,
    FireMonsterEffect,
    ForceMonsterEffect,
    GravityMonsterEffect,
    HellfireMonsterEffect,
    HolyFireMonsterEffect,
    IceMonsterEffect,
    InertiaMonsterEffect,
    JamDoorMonsterEffect,
    LightMonsterEffect,
    LightWeakMonsterEffect,
    MakeDoorMonsterEffect,
    MakeElderSignMonsterEffect,
    MakeTrapMonsterEffect,
    ManaMonsterEffect,
    MeteorMonsterEffect,
    MissileMonsterEffect,
    NetherMonsterEffect,
    NexusMonsterEffect,
    UnnoticedMonsterEffect,
    NukeMonsterEffect,
    OldCloneMonsterEffect,
    OldConfuseMonsterEffect,
    OldDrainLifeMonsterEffect,
    OldHealMonsterEffect,
    OldPolymorphMonsterEffect,
    OldSleepMonsterEffect,
    OldSlowMonsterEffect,
    OldSpeedMonsterEffect,
    PlasmaMonsterEffect,
    PoisonGasMonsterEffect,
    PsiDrainMonsterEffect,
    PsiMonsterEffect,
    ShardMonsterEffect,
    SoundMonsterEffect,
    StasisMonsterEffect,
    StoneWallMonsterEffect,
    StunMonsterEffect,
    TelekinesisMonsterEffect,
    TeleportAwayAllMonsterEffect,
    TeleportAwayEvilMonsterEffect,
    TeleportAwayUndeadMonsterEffect,
    TimeMonsterEffect,
    TurnAllMonsterEffect,
    TurnEvilMonsterEffect,
    TurnUndeadMonsterEffect,
    WallToMudMonsterEffect,
    WaterMonsterEffect,
    WizardBoltMonsterEffect,
}
