// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”

namespace AngbandOS.Core.Borg;

internal static class borg_skill
{
    //BI_STR,
    //BI_INT,
    //BI_WIS,
    //BI_DEX,
    //BI_CON,
    //BI_CSTR,
    //BI_CINT,
    //BI_CWIS,
    //BI_CDEX,
    //BI_CCON,
    //BI_SSTR,
    //BI_SINT,
    //BI_SWIS,
    //BI_SDEX,
    //BI_SCON,
    //BI_LIGHT,
    //BI_CURHP,
    //BI_MAXHP,
    //BI_CURSP,
    //BI_MAXSP,
    //BI_SP_ADJ,
    //BI_FAIL1,
    //BI_FAIL2,
    public static int BI_CLEVEL;
    public static int BI_MAXCLEVEL;
    //BI_ESP,
    //BI_CURLITE,
    //BI_RECALL,
    //BI_FOOD,
    //BI_SPEED,
    //BI_MOD_MOVES,
    //BI_DAM_RED,
    //BI_SDIG,
    //BI_FEATH,
    //BI_REG,
    //BI_SINV,
    //BI_INFRA,
    //BI_DISP,
    //BI_DISM,
    //BI_DEV,
    //BI_SAV,
    //BI_STL,
    //BI_SRCH,
    //BI_THN,
    //BI_THB,
    //BI_THT,
    //BI_DIG,
    //BI_IFIRE,
    //BI_IACID,
    //BI_ICOLD,
    //BI_IELEC,
    //BI_IPOIS,
    //BI_TRFIRE,
    //BI_TRCOLD,
    //BI_TRACID,
    //BI_TRPOIS,
    //BI_TRELEC,
    //BI_RFIRE,
    //BI_RCOLD,
    //BI_RELEC,
    //BI_RACID,
    //BI_RPOIS,
    //BI_RFEAR,
    //BI_RLITE,
    //BI_RDARK,
    //BI_RBLIND,
    //BI_RCONF,
    //BI_RSND,
    //BI_RSHRD,
    //BI_RNXUS,
    //BI_RNTHR,
    //BI_RKAOS,
    //BI_RDIS,
    //BI_HLIFE,
    //BI_FRACT,
    //BI_SRFIRE,
    //BI_SRCOLD,
    //BI_SRELEC,
    //BI_SRACID,
    //BI_SRPOIS,
    //BI_SRFEAR,
    //BI_SRLITE,
    //BI_SRDARK,
    //BI_SRBLIND,
    //BI_SRCONF,
    //BI_SRSND,
    //BI_SRSHRD,
    //BI_SRNXUS,
    //BI_SRNTHR,
    //BI_SRKAOS,
    //BI_SRDIS,
    //BI_SHLIFE,
    //BI_SFRACT,

    //BI_DEPTH,
    //BI_CDEPTH,
    //BI_MAXDEPTH,
    public static bool BI_KING;

    //BI_ISWEAK,
    //BI_ISHUNGRY,
    //BI_ISFULL,
    //BI_ISGORGED,
    //BI_ISBLIND,
    //BI_ISAFRAID,
    //BI_ISCONFUSED,
    //BI_ISPOISONED,
    //BI_ISCUT,
    //BI_ISSTUN,
    //BI_ISHEAVYSTUN,
    //BI_ISPARALYZED,
    //BI_ISIMAGE,
    //BI_ISFORGET,
    //BI_ISENCUMB,
    //BI_ISSTUDY,
    public static bool BI_ISFIXLEV;
    public static bool BI_ISFIXEXP;
    //BI_ISFIXSTR,
    //BI_ISFIXINT,
    //BI_ISFIXWIS,
    //BI_ISFIXDEX,
    //BI_ISFIXCON,
    //BI_ISFIXALL,

    //BI_ARMOR,
    //BI_TOHIT,
    //BI_TODAM,
    //BI_WTOHIT,
    //BI_WTODAM,
    //BI_BTOHIT,
    //BI_BTODAM,
    //BI_BLOWS,
    //BI_SHOTS,
    //BI_WMAXDAM,
    //BI_WBASEDAM,
    //BI_BMAXDAM,
    //BI_HEAVYWEPON,
    //BI_HEAVYBOW,
    //BI_AMMO_COUNT,
    //BI_AMMO_TVAL,
    //BI_AMMO_SIDES,
    //BI_AMMO_POWER,
    //BI_AMISSILES,
    //BI_AMISSILES_SPECIAL,
    //BI_AMISSILES_CURSED,
    //BI_QUIVER_SLOTS,
    //BI_FIRST_CURSED,
    //BI_WHERE_CURSED,

    //BI_CRSTELE,
    //BI_CRSPOIS,
    //BI_CRSSIREN,
    //BI_CRSHALU,
    //BI_CRSPARA,
    //BI_CRSSDEM,
    //BI_CRSSDRA,
    //BI_CRSSUND,
    //BI_CRSSTONE,
    //BI_CRSNOTEL,
    //BI_CRSTWEP,
    //BI_CRSUNKNO,
    //BI_CRSAGRV,
    //BI_CRSHPIMP,
    //BI_CRSMPIMP,
    //BI_CRSFEAR,
    //BI_CRSDRAIN_XP,
    //BI_CRSFVULN,
    //BI_CRSEVULN,
    //BI_CRSCVULN,
    //BI_CRSAVULN,
    //BI_WS_ANIMAL,
    //BI_WS_EVIL,
    //BI_WS_UNDEAD,
    //BI_WS_DEMON,
    //BI_WS_ORC,
    //BI_WS_TROLL,
    //BI_WS_GIANT,
    //BI_WS_DRAGON,
    //BI_WK_UNDEAD,
    //BI_WK_DEMON,
    //BI_WK_DRAGON,
    //BI_W_IMPACT,
    //BI_WB_ACID,
    //BI_WB_ELEC,
    //BI_WB_FIRE,
    //BI_WB_COLD,
    //BI_WB_POIS,
    //BI_APHASE,
    //BI_ATELEPORT,
    //BI_AESCAPE,
    //BI_AFUEL,
    //BI_AHEAL,
    //BI_AEZHEAL,
    //BI_ALIFE,
    //BI_AID,
    //BI_ASPEED,
    //BI_ASTFMAGI,
    //BI_ASTFDEST,
    //BI_ATPORTOTHER,
    //BI_ACUREPOIS,
    //BI_ADETTRAP,
    //BI_ADETDOOR,
    //BI_ADETEVIL,
    //BI_AMAGICMAP,
    //BI_ARECHARGE,
    //BI_ALITE,
    //BI_APFE,
    //BI_AGLYPH,
    //BI_ACCW,
    //BI_ACSW,
    //BI_ACLW,
    //BI_ARESHEAT,
    //BI_ARESCOLD,
    //BI_ARESPOIS,
    //BI_ATELEPORTLVL,  /* scroll of teleport level */
    //BI_AHWORD,            /* Holy Word prayer */
    //BI_AMASSBAN,    /* ?Mass Banishment */
    //BI_ASHROOM,
    //BI_AROD1,       /* Attack rods */
    //BI_AROD2,       /* Attack rods */
    //BI_DINV,    /* See Inv Spell Legal */
    //BI_WEIGHT,

    //BI_MAX
}
