// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”

namespace AngbandOS.Core;

internal enum ProjectileNamesEnum
{
    AcidProjectile,
    ArrowProjectile,
    ChaosProjectile,
    CharmProjectile,
    ColdProjectile,
    ConfusionProjectile,
    ControlAnimalProjectile,
    ControlUndeadProjectile,
    DarknessProjectile,
    DarknessWeakProjectile,
    DeathRayProjectile,
    DestroyTrapOrDoorProjectile,
    DestroyTrapProjectile,
    DisenchantProjectile,
    DisintegrateProjectile,
    DispelAllProjectile,
    DispelDemonProjectile,
    DispelEvilProjectile,
    DispelGoodProjectile,
    DispelLivingProjectile,
    DispelUndeadProjectile,
    DominationProjectile,
    ElectricityProjectile,
    ExplodeProjectile,
    FireProjectile,
    FloorEffectScripts,
    ForceProjectile,
    GravityProjectile,
    HellfireProjectile,
    HolyFireProjectile,
    IceProjectile,
    InertiaProjectile,
    ItemEffectScripts,
    JamDoorProjectile,
    LightProjectile,
    LightWeakProjectile,
    MakeDoorProjectile,
    MakeElderSignProjectile,
    MakeTrapProjectile,
    ManaProjectile,
    MeteorProjectile,
    MissileProjectile,
    MonsterEffectScripts,
    NetherProjectile,
    NexusProjectile,
    NoProjectile,
    NukeProjectile,
    OldCloneProjectile,
    OldConfuseProjectile,
    OldDrainLifeProjectile,
    OldHealProjectile,
    OldPolymorphProjectile,
    OldSleepProjectile,
    OldSlowProjectile,
    OldSpeedProjectile,
    PlasmaProjectile,
    PlayerEffectScripts,
    PoisonGasProjectile,
    PsiDrainProjectile,
    PsiProjectile,
    ShardProjectile,
    SoundProjectile,
    StasisProjectile,
    StoneWallProjectile,
    StunProjectile,
    TelekinesisProjectile,
    TeleportAwayAllProjectile,
    TeleportAwayEvilProjectile,
    TeleportAwayUndeadProjectile,
    TimeProjectile,
    TurnAllProjectile,
    TurnEvilProjectile,
    TurnUndeadProjectile,
    WallToMudProjectile,
    WaterProjectile,
    WizardBoltProjectile,
}