// AngbandOS: 2022 Marc Johnston
//
// This game is released under the “Angband License”, defined as: “© 1997 Ben Harrison, James E.
// Wilson, Robert A. Koeneke This software may be copied and distributed for educational, research,
// and not for profit purposes provided that this copyright and statement are included in all such
// copies. Other copyrights may also apply.”

namespace AngbandOS.Core.MonsterSpells;

[Serializable]
internal abstract class CauseWoundsMonsterSpell : MonsterSpell
{
    protected CauseWoundsMonsterSpell(Game game) : base(game) { }

    public override void Bind()
    {
        base.Bind();
        DamageRoll = Game.ParseExpression(DamageRollExpression);
    }

    public override bool IsAttack => true;
    public override bool Annoys => true;

    public override string? VsPlayerBlindMessage => "You hear someone mumble.";

    public override string? VsPlayerActionMessage => "{0} points at you and curses.";

    /// <summary>
    /// Returns the roll expression that determines the amount of damage the arrow projectile inflicts.  This expression is parse
    /// to generate the DamageDiceRoll.
    /// </summary>
    protected abstract string DamageRollExpression { get; }

    /// <summary>
    /// Returns the roll that determines the amount of damage the arrow projectile inflicts.  This dice roll is generated by
    /// parsing the DamageDiceRollExpression property during binding.
    /// </summary>
    protected Expression DamageRoll { get; private set; }

    /// <summary>
    /// Returns the chance that an item of equipment that the player is wearing will be cursed.
    /// </summary>
    protected abstract int CurseEquipmentChance { get; }

    /// <summary>
    /// Returns the chance that an item of equipment that the player is wearing will be heavily cursed.
    /// </summary>
    protected abstract int HeavyCurseEquipmentChance { get; }

    /// <summary>
    /// Returns an additional amount of time the player will bleed.  Returns 0, by default.
    /// </summary>
    protected virtual int TimedBleeding => 0;
    public override void ExecuteOnPlayer(Monster monster)
    {
        if (base.Game.RandomLessThan(100) < Game.SkillSavingThrow)
        {
            Game.MsgPrint("You resist the effects!");
        }
        else
        {
            string monsterDescription = monster.IndefiniteVisibleName;

            Game.CurseEquipment(CurseEquipmentChance, HeavyCurseEquipmentChance);
            int damage = Game.ComputeIntegerExpression(DamageRoll).Value;
            Game.TakeHit(damage, monsterDescription);

            if (TimedBleeding > 0)
            {
                Game.BleedingTimer.AddTimer(TimedBleeding);
            }
        }
    }

    public override void ExecuteOnMonster(Monster monster, Monster target)
    {
        int rlev = monster.Race.Level >= 1 ? monster.Race.Level : 1;
        string targetName = target.Name;
        bool blind = Game.BlindnessTimer.Value != 0;
        bool seeTarget = !blind && target.IsVisible;
        MonsterRace targetRace = target.Race;

        if (targetRace.Level > base.Game.DieRoll(rlev - 10 < 1 ? 1 : rlev - 10) + 10)
        {
            if (seeTarget)
            {
                Game.MsgPrint($"{targetName} resists!");
            }
        }
        else
        {
            int damage = Game.ComputeIntegerExpression(DamageRoll).Value;
            target.TakeDamageFromAnotherMonster(damage, out _, " is destroyed.");
        }
    }
}
